### ISSUE TITLE
Clear out entire cache directory

### ISSUE THREAD

**Issue by ngan** [ledermann/docker-rails-base#1091]
Just noticed this line:
https://github.com/ledermann/docker-rails-base/blob/f9abbbedc9d2eb57b57cdc7b0ede2f2dd69d42c6/Builder/Dockerfile#L35

It only clears out `.gem` caches. If you have a gem that is referencing a `git` repo, the cache there will be the entire repo itself. I think it's safe to clear out the entire `cache/*` directory instead of looking only for `*.gem` files.

**Comment by ledermann** [comment]
Yes, this seems legit, so I changed it. Thanks!

BTW, I found this discussion recommending the same thing:
https://github.com/rubygems/rubygems/issues/3225
