### ISSUE TITLE
assets:compile task is tied to Sprockets

### ISSUE THREAD

**Issue by Quintasan** [ledermann/docker-rails-base#112]
I'm actively trying to get rid of sprockets since we already have Webpack in Rails applications but calling `assets:compile` is tied to Sprockets which makes my build fail with

```
rails aborted!
LoadError: cannot load such file -- uglifier
```

As far as I am concerned you can call `webpacker:compile` to get packs compiled.

Would you consider supporting NOT calling `assets:precompile`?

**Comment by Quintasan** [comment]
I think we could append `; exit 0` to https://github.com/ledermann/docker-rails-base/blob/master/Builder/Dockerfile#L44 and add `bundle exec rails assets:precompile; exit 0` so we can have both.

The obvious downside here is that the build will succeed even if there were any other problem when building assets :(

**Comment by ledermann** [comment]
I agree that moving away from Sprockets makes sense. But: The task `assets:precompile` is available with Webpacker, too - as you can see in the [docs](https://github.com/rails/webpacker/#deployment):

> Webpacker hooks up a new webpacker:compile task to assets:precompile, which gets run whenever you run assets:precompile. If you are not using Sprockets, webpacker:compile is automatically aliased to assets:precompile. 

I'm using `docker-rails-base` for multiple Rails applications - some of them use Webpacker only, others use Sprockets. There are no issues about assets compiling, running `assets:precompile` works for all of them.

Maybe you have something like `config.assets.js_compressor = :uglifier` in your config files?

**Comment by Quintasan** [comment]
> Maybe you have something like `config.assets.js_compressor = :uglifier` in your config files?

Ha, you were right about this! Closing.
