### ISSUE TITLE
Update to Ruby 3.1 and Rails 7.0.1

### ISSUE THREAD

**Issue by wagnerpereira** [ledermann/docker-rails-base#1166]

**Comment by wagnerpereira** [comment]
Hey @ledermann happy new year and thank you alot for all your work in this project. I tried to help you in this upgrade. I need this new image to upgrade some projects to Rails 7.0.1 and Ruby 3.1.

It's my first colaboration so sorry for any mistake.

I think the only adjust needed is the date of the plublication of this new image on Readme.md.

Cheers!

**Comment by ledermann** [comment]
Hi @wagnerpereira, thanks a lot for your work and your interest in this project! 

I've created a separate commit instead of merging your PR, so it's more atomic (without gems changed but with updated Bundler version). Closed by 7baa24068efe43d587fbb85a54d73ba3f241569c
