### ISSUE TITLE
Feature request: add gcompat for tailwindcss(-rails)

### ISSUE THREAD

**Issue by itsyoshio** [ledermann/docker-rails-base#1184]
[tailwindcss-rails](https://github.com/rails/tailwindcss-rails) or rather [tailwindcss-cli](https://github.com/tailwindlabs/tailwindcss) requires `build-base` and `gcompat` in order to compile Tailwind.

Related Issue [here](https://github.com/tailwindlabs/tailwindcss/issues/6690#issuecomment-1002213735)

I'm aware that the Builder [Dockerfile](https://github.com/ledermann/docker-rails-base/blob/fad7927f6ae893157e1ee7975b7e06a9b3a750d7/Builder/Dockerfile#L6) is meant for Rails 6 currently,\
but would it be possible for you to include `gcompat` aswell?

Appreciated!

PS:\
had 4m50s builds with your base images on Rails 6.1\
after switching to Rails 7 i got 2m30s on the Build Stage

**Comment by ledermann** [comment]
Just added `gcompact` package, does this help? In my apps I'm using `esbuild` or `webpack`, so I didn't stumbled upon missing Alpine packages.

BTW: A few weeks ago I [upgraded](f7a2e44fcadc6336264402e8838e170f2c56f8ea) the Builder stuff to Rails 7, so it is faster to build a Rails 7 app than a Rails 6 app.

In my apps building time is about 1-2 minutes on GitHub Actions, see these examples which both use esbuild:

* 1:12m (https://github.com/solectrus/solectrus/runs/4832994286?check_suite_focus=true)
* 1:36m (https://github.com/ledermann/templatus-hotwire/runs/4831998237?check_suite_focus=true)

**Comment by itsyoshio** [comment]
Thanks! Works like a Charm.
Getting 2m13s Builds now.

I'm on Gitlab with their public Runners & selfhosted ones on Kubernetes.\
Definitely interested in Base Images for Rails 7.

**Comment by ledermann** [comment]
Cool, thanks for the feedback!

> Definitely interested in Base Images for Rails 7.

Please note that this project **is** already ready on Rails 7. Means: The `Builder` image includes the gems `rails`, `activerecord`, etc. in version `7.0.1`, so building an image for your Rails 7 app should be as fast as possible.
