### ISSUE TITLE
Set ENV var before bundling for gems like sidekiq-pro

### ISSUE THREAD

**Issue by weilandia** [ledermann/docker-rails-base#1640]
Is there a way to pass ENV vars to the container before bundling?

**Comment by ledermann** [comment]
I've just made a change to the `Builder` Dockerfile. If your Sidekiq credentials are included in your `~/.bundle/config` file, you can inject this file via secret:

```docker
docker buildx build --secret id=bundleconfig,src=$HOME/.bundle/config .
```

@weilandia Does this help?

**Comment by weilandia** [comment]
This helps! Thanks @ledermann
