### ISSUE TITLE
No 3.3.4 Tag in Dockerhub?

### ISSUE THREAD

**Issue by itsyoshio** [ledermann/docker-rails-base#2410]
The Dockerhub doesn't seem to have received a published tag for the latest Ruby Version from July.

[DockerHub Tag 3.3.4](https://hub.docker.com/r/ledermann/rails-base-builder/tags?page=&page_size=&ordering=&name=3.3.4)

is this intended? I saw that Dependabot updated the Repo to 3.3.4.

**Comment by ledermann** [comment]
Since [a change from June 20](https://github.com/ledermann/docker-rails-base/commit/0dde97c489df4587e8cc37dee919b1a94659782c), the images are not pushed to Docker Hub anymore. Please pull them from `ghcr.io`.
