### ISSUE TITLE
filesystem layer verification failed for digest sha256

### ISSUE THREAD

**Issue by andrewlynch** [ledermann/docker-rails-base#349]
My builds have started returning `filesystem layer verification failed for digest sha256`. Even rebuilding old images and trying to pull them is failing. Is it possible the lastest commit is breaking ?

**Comment by ledermann** [comment]
It seems to me that this error messages are caused from pulling the images, not from building. But for me, the following commands are running fine:

```
 docker pull ledermann/rails-base-builder
 docker pull ledermann/rails-base-final
```

I use these images for my daily work in many applications without any problems. Do you have any further informations about the error?

BTW: The `Builder` and `Final` images are regularly (mostly daily) updated by dependabot, there is no image tagging yet. So if there was an issue yesterday, this can be different today.

**Comment by andrewlynch** [comment]
Thanks @ledermann, dependabot updated the repo and my images are now pulling successfully again.
