### ISSUE TITLE
SECRET_KEY_BASE=dummy - a security risk?

### ISSUE THREAD

**Issue by davidalejandroaguilar** [ledermann/docker-rails-base#83]
Just noticed that the base Dockerfile precompile step has `SECRET_KEY_BASE=dummy `. Isn't this a security risk? 

There are a few workarounds here: https://github.com/rails/rails/issues/32947 that could make it more secure, such as using `SECRET_KEY_BASE=``bin/rake secret`` bin/rake assets:precompile`.

**Comment by ledermann** [comment]
I don't think this is a security risk, because the dummy key is used for compiling assets only. It's **NOT** used for running the application. 

Of course, using a constant dummy value is just a hack, but I don't see why using a real secret would be more secure in this case. Am I missing something?

**Comment by davidalejandroaguilar** [comment]
I guess you're right, this was more like a question really, since I'm not sure either if it affects in any way.

**Comment by kaka-ruto** [comment]
@ledermann this no longer works in Rails 6.1. I couldn't find any workaround on the interwebs - the only thing that works is using the actual master key, as if you pass a dummy one, it tries accessing the database and fails thereof.

**Comment by ledermann** [comment]
@kaka-ruto I have no such issues with my Rails 6.1 applications. What error message do you get? Are you sure this is because of a different SECRET_KEY_BASE? If not, please open a new issue to not mix things up.

**Comment by kaka-ruto** [comment]
@ledermann , did you mean I can use the real SECRET_KEY_BASE value stored on my credentials? I was using a dummy one, i'e `SECRET_KEY_BASE=1 RAILS_ENV=production bin/rails assets:precompile` and it doesn't work.

This is the error message that I get

```
Missing encryption key to decrypt file with. Ask your team for your master key and write it to /app/config/credentials/production.key or put it in the ENV['RAILS_MASTER_KEY'].
#19 ERROR: executor failed running [/bin/sh -c SECRET_KEY_BASE=1 RAILS_ENV=production bin/rails assets:precompile]: exit code: 1
------
 [production 3/3] RUN SECRET_KEY_BASE=1 RAILS_ENV=production bin/rails assets:precompile:
```
